genome_grist/conf/Snakefile
genome_grist/prefetch_gather.py
snakemake.slurm

Use a prefetch approach to speed up gather, per https://github.com/dib-lab/sourmash/issues/1226.
This will eventually be integrated into sourmash natively, but it's such a persistent problem for genome-grist that I'm integrating it here first!

Add prefetching of containment matches to speed up gather

---

.gitignore
Makefile
genome_grist/combine_csvs.py
genome_grist/conf/Snakefile
genome_grist/conf/env/genbank.yml
genome_grist/conf/env/sourmash.yml
genome_grist/genbank_genomes.py

This PR introduces snakemake checkpoints into genome-grist to make all the rules run end-to-end. Also adds some other cleanup/streamlining.
Specifically,
* use the checkpoint-class-style hack I introduced in charcoal in https://github.com/dib-lab/charcoal/pull/163 to get the genome accessions from gather
* updates the sourmash environment with 4.0.0a3 wheel, for now
TODO:

Use checkpoints to provide an end-to-end workflow

---

genome_grist/__main__.py
genome_grist/conf/Snakefile
genome_grist/gather_split.py
genome_grist/prefetch_gather.py

This PR adjusts the Snakefile so that `sample` is now a wildcard, allowing multiple samples to be provided via config.
Among other things, this PR dramatically speeds up the actual sourmash gather step by running gather only on the known hashes.
Other updates and modifications:
Closes #32

Allow input samples to be a list

---

genome_grist/conf/Snakefile
genome_grist/gather_split.py
genome_grist/prefetch_gather.py

adjust thresholds and add --scaled argument, in order to support higher-resolution signatures (for protein) and smaller matches (virus).

adjustments for virus and protein

---

genome_grist/conf/Snakefile

Follows #38 and makes relevant settings for (a) virus and (b) protein searches accessible via config files.
Example config parameters for virus searches:
```
sourmash_database_glob_pattern: /group/ctbrowngrp/virus-references/pigeon/index/pigeon1.0.nucleotide-k31-scaled1000.sbt.zip
sourmash_database_threshold_bp: 0
```
and for protein:
```
sourmash_compute_ksizes:
- 11
sourmash_sigtype: protein
sourmash_database_glob_pattern: /home/ntpierce/thumper/databases/gtdb95-genus-n0.protein-k11-scaled100.sbt.zip
sourmash_database_ksize: 33
sourmash_database_threshold_bp: 50e3
```

Support virus and protein searches via config file

---

genome_grist/conf/Snakefile
genome_grist/gather_split.py
tests/test-data/HSMA33MX-subset.conf

This PR adds per-sample reporting on number of reads, number of bases, number of k-mers (estimated), and the total/known/unknown hashes in the sourmash signature.
The final output of this PR is a new file, `{sample}.info.yaml`, that contains info like this:
```
kmers: 282917158
known_hashes: 102436
n_bases: 4174333719
n_reads: 43053600
sample: p8808mo11
total_hashes: 284161
unknown_hashes: 181725
```
TODO:
- XXX provide a summary report somewhere/somehow (jupyter notebook? text file? html file? markdown?) - moved to https://github.com/dib-lab/genome-grist/issues/60

[MRG] add more reporting output read/kmer stats

---

genome_grist/conf/Snakefile
tests/test_snakemake.py

Fixes https://github.com/dib-lab/genome-grist/issues/45, which was caused by dropping track-abundance from signature calculations by mistake when switch to using `sourmash sketch` from `sourmash compute` 🤦 .

[MRG] Fix abundance calculations

---

environment.yml
genome_grist/conf/env/sourmash.yml

Closes #73, I think?
- adds mamba to `environment yml` 
- update sourmash to 4.x (`environment.yml`; `genome_grist/conf/env/sourmash.yml`)
Note: this is just one way to solve #73. 
Alternatives:
- handle via `pip` in `setup.py`
- install `mamba` in the `test.yml` workflow
Happy to change to whatever option you prefer.

[MRG] Install mamba and use sourmash 4.x

---

genome_grist/conf/Snakefile
genome_grist/conf/env/trim.yml

Benefits:
- don't need to choose or download adapters (detected automatically!)
- outputs interleaved files!  (can output pe if you want)
- doesn't need to output unpaired files from pe (can output if you want)
Optional Features (I included, but can remove it you want) --
- optional low complexity filter (https://github.com/OpenGene/fastp#low-complexity-filter)
>Low complexity filter is disabled by default, and you can enable it by -y or --low_complexity_filter. The complexity is defined as the percentage of base that is different from its next base (base[i] != base[i+1]). For example:
>#### a 51-bp sequence, with 3 bases that is different from its next base
>seq = 'AAAATTTTTTTTTTTTTTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGCCCC'
>complexity = 3/(51-1) = 6%
>The threshold for low complexity filter …

use fastp instead of trimmomatic

---

environment.yml
genome_grist/conf/Snakefile
genome_grist/conf/env/sourmash.yml
genome_grist/conf/env/sra.yml
genome_grist/gather_split.py
tests/test-data/HSMA33MX.conf

This PR switches to using the `.zip` output format for prefetch, which should require less memory (among other things).
While I'm at it, I upgraded requirements to sourmash v4.1.1, which was just released.
Also, here I downgrade sra-tools to 2.10.0, because 2.11.0 core dumps with an unhandled exception on my Mac laptop. This may be because [of the vdb-config confusion](https://github.com/ncbi/sra-tools/issues/77#issuecomment-635478745), or may not. 🤷  (I suspect the issue is that my `~/.ncbi/user-settings.mkfg` file, created by vdb-config, is out of date. But I decline to spend any more time on it for now!)

[MRG] switch to using zipfile outputs for prefetch

---

Makefile
README.md
environment.yml
genome_grist/__main__.py
genome_grist/conf/Snakefile
setup.py

This PR:
* changes `summarize` to `summarize_mapping`, in honor of the new `summarize_gather`;
* fixes a problem in the `run` command line where providing options like `-n` prevented help from being output;
* updates snakemake version to 6.5.1 to avoid a `KeyError` problem having to do with checkpoints;
Fixes https://github.com/dib-lab/genome-grist/issues/96
Ready for review & merge @hehouts 
(note, the tests won't pass, but that's ok for now.)

[MRG] change default targets and update help docs

---

genome_grist/conf/Snakefile
genome_grist/conf/env/sourmash.yml

sourmash v4.2.1 contains the `prefetch` picklist type added in https://github.com/sourmash-bio/sourmash/pull/1660. This PR changes genome-grist to use that.

[MRG] update to use ::prefetch metatype for picklist

---

README.md
genome_grist/conf/Snakefile

Fixes #108 
I don't know why `fasterq-dump` can't process the **experiment name**, but the **Run ID** works as expected.
Experiment: https://www.ncbi.nlm.nih.gov/sra/?term=HSMA33MX
Run: https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR5950647
---
To test:
```
fasterq-dump HSMA33MX -p --split-files ## Will fail
fasterq-dump SRR5950647 -p --split-files ## Will work
```

[MRG] Fix README Tutorial Example

---

environment.yml
genome_grist/conf/Snakefile
genome_grist/conf/env/papermill.yml
genome_grist/conf/env/sourmash.yml
genome_grist/notebooks/report-mapping.ipynb
setup.py

This PR does some cleanup after #128, partly motivated by #124.
* checks for periods in sample names
* updates versions for snakemake, sourmash, and papermill
* removes the `/depth/` subdirectory (motivated by changes in #124!)
* removes plotly (unused)
Fixes #127 by checking for periods in sample names.
Fixes https://github.com/dib-lab/genome-grist/issues/117.

[MRG] several minor updates and cleanup

---

conf-private.yml
genome_grist/conf/Snakefile

Note: PR into https://github.com/dib-lab/genome-grist/pull/130
Addresses #132 by adding a `picklist:` config file parameter that lets you subselect on genomes.
TODO:

[WIP] add picklist support to config file

---

genome_grist/conf/Snakefile
tests/test_snakemake.py

For no good reason, the .sig files produced by genome-grist are not compressed, despite sourmash supporting it natively. This fixes that by putting a .gz suffix on everything.
Fixes https://github.com/dib-lab/genome-grist/issues/156

[MRG] compress output signatures

---

genome_grist/conf/Snakefile

A long time ago, in a galaxy far, far away, we updated genome-grist to run gather only on the known bits of the metagenome signature - looks like it was in https://github.com/dib-lab/genome-grist/pull/29. Then we slowly updated things to use prefetch to calculate the known bits, and switched to using manifests, etc. etc. etc. And finally we fixed `sourmash gather` to do the split properly internally, over in https://github.com/sourmash-bio/sourmash/pull/1613. But we never updated genome-grist, so all of the genome-grist `gather` output files contained the wrong "% known" in the output!
This PR fixes that; the gather output will now contain the correct fraction of the sample that is (un)known.
Fixes https://github.com/dib-lab/genome-grist/issues/163

[MRG] fix and adjust gather-based known/unknown reporting

---

doc/configuring.md

This PR changes the docs config file `sample` parameter to `samples` to be compatible with the grist latest version.

[MRG] fix local genomes config file in docs

---

genome_grist/__main__.py

In https://github.com/dib-lab/genome-grist/pull/195, I changed the return value of `run_snakemake` to be a `CompletedProcess` instance as returned by `subprocess.run(...)` [ref](https://docs.python.org/3/library/subprocess.html#subprocess.run). This broke the bits of the code that use `sys.exit(run_snakemake(...))` to signal success or failure on CLI execution.
This PR fixes the returncode to be the value of `CompletedProcess.returncode`.

[MRG] fix exit codes from genome-grist CLI

---

doc/configuring.md
genome_grist/copy_local_genomes.py

`genome_grist.copy_local_genomes` takes forever to copy and compress FASTA files. This PR resolves #138 by adding the command line option `--sym` to use symbolic links. `--sym` defaults to False, might be changed later after discussing the PR.
Also upgrading private genomes config file to the latest version in docs (`samples` instead of `sample`).

[MRG] Speed up `copy_local_genomes.py` with symbolic links

---

genome_grist/conf/Snakefile

Fixes https://github.com/dib-lab/genome-grist/issues/191

[MRG] fix trim-low-abund ksize to match analysis ksize

---

genome_grist/conf/Snakefile

This PR fixes the calculation of resources needed for sourmash prefetch, so that snakemake will correctly run more things in parallel when given the resources to do so.
(MB == 1 m == 1e6, not 1e3...)

[MRG] fix calculation of memory required for prefetch step.

---

doc/quickstart.md
genome_grist/conf/Snakefile
tests/test-data/SRR5950647.conf

Fix `download_matching_genome_wc` which was erroneously using `gzip.open`; switch it over to using `load_csv`.
Also adjust `zip` target rule to create a named .zip file.

[MRG] fix genome download rule

---

genome_grist/conf/Snakefile

This fixes a test failure caused by sourmash:
```
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
```
by turning off breaking errors for DeprecationWarning.
See https://github.com/sourmash-bio/sourmash/issues/2425#issuecomment-1440068864 for further discussion.

MRG: Ignore DeprecationWarning from sourmash in tests.

---

Makefile
pyproject.toml

- v0.11.3 pip install was not including `Snakefile`
- add Snakefile as pkg data in `pyproject.toml`
This seems to fix on my end, and the `Snakefile` moved location in #313. The `env` folder also moved in #313, but it seems to be included in the install already.

MRG: include Snakefile in pkg again
