dib-lab/genome-grist

Makefile
conf.yml
genome_grist/__init__.py
genome_grist/__main__.py
genome_grist/conf/Snakefile
genome_grist/conf/defaults.conf
genome_grist/conf/system.conf
genome_grist/genbank_genomes.py
genome_grist/notebooks/report-sample.ipynb
genome_grist/prefetch_gather.py
tests/test-data/HSMA33MX-subset.conf
tests/test-data/HSMA33MX.conf

This PR:
* adds memory, sourmash ksize, and sourmash db path pattern/ksize/scaled config options
* adds defaults and system config files
* update `make test` to use config files, test more of `prefetch_gather`, etc.

upgrade configurability!

---

genome_grist/conf/Snakefile

Failed to push all the commits on #22, sigh. Here they are.

Add miscellaneous functionality, catchup.

---

genome_grist/conf/Snakefile
genome_grist/genbank_genomes.py

Add some reporting output, add configuration parameter PREFETCH_MEMORY, and adjust names/clean up.

Misc cleanup

---

genome_grist/conf/Snakefile
genome_grist/conf/env/sra.yml
genome_grist/conf/env/trim.yml

One more commit that should have been on #33

More fix unpaired data sets

---

README.md

update README with memory requirements and other text

---

genome_grist/genbank_genomes.py

This edit is to address #55, where the FTP connection timed out when running the genome-grist readme tutorial in WDL/on Cromwell.
@ctb

Change ftp to https

---

genome_grist/conf/Snakefile
tests/test_snakemake.py

Adds a test for https://github.com/dib-lab/genome-grist/pull/56

[MRG] Add tests for sample summary info

---

environment.yml
genome_grist/conf/Snakefile
genome_grist/conf/env/sourmash.yml

* updates sourmash deps to use 4.0.0rc1
* updates screed deps to 1.0.5 or later
* turns deprecations into warnings

[WIP] update sourmash deps to 4.0.0rc1

---

genome_grist/__main__.py
genome_grist/conf/Snakefile

Add some basic command line docs for `genome-grist run`.

[MRG] add CLI usage info for `genome-grist run`

---

.github/workflows/test.yml
environment.yml
setup.cfg
setup.py

Update snakemake &c dependencies in conda and Python install.

[MRG] update dependencies in setup.py and environment.yml

---

genome_grist/conf/Snakefile

Per @hehouts, sometimes it's not clear what config options are missing. This makes it clearer.
@hehouts can you review, please?

[MRG] make missing config options clearer

---

environment.yml
setup.py

[MRG] Update Snakemake version

---

environment.yml
genome_grist/conf/env/papermill.yml
genome_grist/conf/env/sourmash.yml

[MRG] update Python versions in environments

---

Makefile
genome_grist/__main__.py
genome_grist/conf/Snakefile
tests/test-data/SRR5950647.conf
tests/test-data/SRR5950647.subset.conf

Fixes https://github.com/dib-lab/genome-grist/issues/119
Adds tests, too!

[MRG] Fix `download_matching_genomes` target

---

genome_grist/combine_csvs.py
genome_grist/conf/Snakefile
genome_grist/summarize_mapping.py

This cherry-picks the very useful VCF-calculating code from #124 into the main branch.

[MRG] add VCF-calculating code from #124

---

.github/dependabot.yml

Add `.github/dependabot.yml` per [instructions](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates)

[MRG] add dependabot

---

.github/workflows/run_tests.yml

run GitHub actions regularly to avoid https://github.com/dib-lab/genome-grist/issues/237#issuecomment-1336257497

[MRG] run actions regularly

---

genome_grist/conf/env/papermill.yml
genome_grist/conf/env/sourmash.yml
setup.cfg

sourmash => 4.6.1 or greater
screed => 1.1 or greater

[MRG] update sourmash and screed versions

---

.github/workflows/gh-pages.yml

[MRG] add gh-pages deploy action

---

environment.yml
genome_grist/conf/Snakefile
genome_grist/conf/env/sra.yml

This PR:
* updates the snakemake version in `environment.yml` to match ...
* Allows sra-toolkit upgrade
* Fixes an error message in Snakefile to be not just helpful but correct

[MRG] update snakemake version in `environment.yml`, & other minor fixes

---

.github/workflows/run_tests.yml

Note: includes https://github.com/dib-lab/genome-grist/pull/257

[MRG] update actions to make sure right version(s) are being used

---

doc/configuring.md

Fixes https://github.com/dib-lab/genome-grist/issues/296

MRG: fix sketch command in configuring doc

---

genome_grist/conf/Snakefile
genome_grist/conf/env/sourmash.yml
genome_grist/summarize_gather_hashes.py

Note: this is a PR into https://github.com/dib-lab/genome-grist/pull/313
TODO -

WIP: Use `sourmash_plugin_branchwater`
